export const PRODUCT_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  DEAD: 'DEAD',
  RISKY: 'RISKY',
  LOW_PROFIT: 'LOW_PROFIT'
});

export const MARKETPLACE_PLATFORM = Object.freeze({
  MEESHO: 'MEESHO',
  AMAZON: 'AMAZON'
});

export const LISTING_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  PAUSED: 'PAUSED',
  DELISTED: 'DELISTED'
});

export const LISTING_HEALTH = Object.freeze({
  HEALTHY: 'HEALTHY',
  RISKY: 'RISKY',
  INACTIVE: 'INACTIVE'
});

export const BUSINESS_RULES = Object.freeze({
  MIN_PROFIT_AMOUNT: 50,
  MIN_PROFIT_MARGIN_PERCENT: 10,
  LOW_STOCK_THRESHOLD: 5,
  MAX_HEALTHY_DELIVERY_DAYS: 7,
  MIN_HEALTHY_RELIABILITY_SCORE: 60,
  DEFAULT_MARKETPLACE_FEES: 0
});

export const SUPPLIER_SCORE_WEIGHTS = Object.freeze({
  AVAILABILITY: 50,
  PRICE: 30,
  RELIABILITY: 20
});

export const SOURCE_TYPES = Object.freeze({
  WEBSITE: 'WEBSITE',
  INDIAMART: 'INDIAMART',
  TELEGRAM: 'TELEGRAM'
});

export const AUTOMATION_LOG_STATUS = Object.freeze({
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  RUNNING: 'RUNNING',
  SKIPPED: 'SKIPPED'
});

export const AUTOMATION_ACTION_TYPES = Object.freeze({
  WEBSITE_CHECK: 'WEBSITE_CHECK',
  TELEGRAM_CONNECT: 'TELEGRAM_CONNECT',
  TELEGRAM_LISTEN: 'TELEGRAM_LISTEN',
  TELEGRAM_MESSAGE: 'TELEGRAM_MESSAGE',
  SOURCE_UPDATE: 'SOURCE_UPDATE',
  SCHEDULER: 'SCHEDULER'
});

export const TELEGRAM_EXTRACTION_STATUS = Object.freeze({
  RAW: 'RAW',
  QUEUED: 'QUEUED',
  PROCESSING: 'PROCESSING',
  EXTRACTED: 'EXTRACTED',
  NO_PRODUCT_SIGNAL: 'NO_PRODUCT_SIGNAL',
  FAILED: 'FAILED'
});

export const REVIEW_STATUS = Object.freeze({
  VERIFIED: 'VERIFIED',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
  LOW_CONFIDENCE: 'LOW_CONFIDENCE',
  AUTO_CONFIRMED: 'AUTO_CONFIRMED',
  REJECTED: 'REJECTED'
});

export const REVIEW_TASK_TYPES = Object.freeze({
  PRODUCT_EXTRACTION: 'PRODUCT_EXTRACTION',
  PRICE_AMBIGUITY: 'PRICE_AMBIGUITY',
  STOCK_AMBIGUITY: 'STOCK_AMBIGUITY',
  SUPPLIER_ACTIVITY: 'SUPPLIER_ACTIVITY'
});

export const REVIEW_PRIORITIES = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
});

export const REVIEW_ASSIGNED_STATUS = Object.freeze({
  OPEN: 'OPEN',
  IN_REVIEW: 'IN_REVIEW',
  RESOLVED: 'RESOLVED'
});

export const TELEGRAM_QUEUE_NAMES = Object.freeze({
  MESSAGE: 'telegram-message-queue',
  EXTRACTION: 'telegram-extraction-queue',
  REVIEW: 'telegram-review-queue'
});
